[package]
name = "cap-std"
version = "0.1.0"
description = "Capability-oriented version of the Rust standard library"
authors = ["Dan Gohman <sunfish@mozilla.com>", "Jakub Konka <kubkon@jakubkonka.com>"]
license = "Apache-2.0 WITH LLVM-exception OR Apache-2.0 OR MIT"
keywords = ["std", "api", "network", "file"]
categories = ["filesystem", "network-programming"]
repository = "https://github.com/sunfishcode/cap-std"
edition = "2018"
readme = "README.md"

[dependencies]
arf-strings = { version = "0.1.2", optional = true }
cap-primitives = { path = "cap-primitives", version = "^0.1.0", default-features = false }

[target.'cfg(unix)'.dependencies]
yanix = "0.19.0"

[target.'cfg(target_os = "wasi")'.dependencies]
yanix = "0.19.0"

[target.'cfg(target_os = "fuchsia")'.dependencies]
yanix = "0.19.0"

[badges]
maintenance = { status = "actively-developed" }

[features]
default = ["no_racy_asserts"]
fs_utf8 = ["arf-strings"]
no_racy_asserts = ["cap-primitives/no_racy_asserts"]

[workspace]
members = [
  "cap-async-std",
  "cap-directories",
  "cap-primitives",
  "cap-std-tests",
  "cap-tempfile",
  # Work around https://github.com/rust-lang/cargo/issues/8338.
  #"fuzz",
]
