[package]
name = "cap-directories"
version = "0.5.0"
description = "Capability-oriented standard directories for config, cache and other data"
authors = [
    "Dan Gohman <dev@sunfishcode.online>",
    "Jakub Konka <kubkon@jakubkonka.com>",
]
license = "Apache-2.0 WITH LLVM-exception OR Apache-2.0 OR MIT"
keywords = ["app_dirs", "path", "folder", "xdg", "basedir"]
categories = ["filesystem"]
repository = "https://github.com/bytecodealliance/cap-std"
edition = "2018"
readme = "README.md"

[dependencies]
cap-std = { path = "../cap-std", version = "^0.5.1-alpha.0"}
directories-next = "2.0.0"

[target.'cfg(not(windows))'.dependencies]
libc = "0.2.80"

[target.'cfg(windows)'.dependencies]
winapi = "0.3.9"

[badges]
maintenance = { status = "actively-developed" }
